server:
  port: 8770
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8660/eureka/
spring:
  application:
    name: product-service
#zipkin服务所在地址
  zipkin:
    base-url: http://192.168.3.222:9411/
#配置采样百分比 开发环境可以设置为1=100%
  sleuth:
    sampler:
      probability: 1